package model;
// Generated Jan 9, 2018 3:15:18 PM by Hibernate Tools 4.3.1



/**
 * TaskManagerClassFiles generated by hbm2java
 */
public class TaskManagerClassFiles  implements java.io.Serializable {


     private Integer id;
     private ClassFiles classFiles;
     private TaskManager taskManager;

    public TaskManagerClassFiles() {
    }

    public TaskManagerClassFiles(ClassFiles classFiles, TaskManager taskManager) {
       this.classFiles = classFiles;
       this.taskManager = taskManager;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ClassFiles getClassFiles() {
        return this.classFiles;
    }
    
    public void setClassFiles(ClassFiles classFiles) {
        this.classFiles = classFiles;
    }
    public TaskManager getTaskManager() {
        return this.taskManager;
    }
    
    public void setTaskManager(TaskManager taskManager) {
        this.taskManager = taskManager;
    }




}


