package model;
// Generated Jan 9, 2018 3:15:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserTask generated by hbm2java
 */
public class UserTask  implements java.io.Serializable {


     private Integer id;
     private ClassFiles classFiles;
     private String name;
     private Set<UserTaskClassFiles> userTaskClassFileses = new HashSet<UserTaskClassFiles>(0);
     private Set<TaskDefinition> taskDefinitions = new HashSet<TaskDefinition>(0);

    public UserTask() {
    }

    public UserTask(ClassFiles classFiles, String name, Set<UserTaskClassFiles> userTaskClassFileses, Set<TaskDefinition> taskDefinitions) {
       this.classFiles = classFiles;
       this.name = name;
       this.userTaskClassFileses = userTaskClassFileses;
       this.taskDefinitions = taskDefinitions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ClassFiles getClassFiles() {
        return this.classFiles;
    }
    
    public void setClassFiles(ClassFiles classFiles) {
        this.classFiles = classFiles;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<UserTaskClassFiles> getUserTaskClassFileses() {
        return this.userTaskClassFileses;
    }
    
    public void setUserTaskClassFileses(Set<UserTaskClassFiles> userTaskClassFileses) {
        this.userTaskClassFileses = userTaskClassFileses;
    }
    public Set<TaskDefinition> getTaskDefinitions() {
        return this.taskDefinitions;
    }
    
    public void setTaskDefinitions(Set<TaskDefinition> taskDefinitions) {
        this.taskDefinitions = taskDefinitions;
    }




}


