package model;
// Generated Jan 9, 2018 3:15:18 PM by Hibernate Tools 4.3.1



/**
 * UserTaskClassFiles generated by hbm2java
 */
public class UserTaskClassFiles  implements java.io.Serializable {


     private Integer id;
     private ClassFiles classFiles;
     private UserTask userTask;

    public UserTaskClassFiles() {
    }

    public UserTaskClassFiles(ClassFiles classFiles, UserTask userTask) {
       this.classFiles = classFiles;
       this.userTask = userTask;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ClassFiles getClassFiles() {
        return this.classFiles;
    }
    
    public void setClassFiles(ClassFiles classFiles) {
        this.classFiles = classFiles;
    }
    public UserTask getUserTask() {
        return this.userTask;
    }
    
    public void setUserTask(UserTask userTask) {
        this.userTask = userTask;
    }




}


